<a href="https://colab.research.google.com/github/Atria14/data-science/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Colab')

Hello Colab


In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.6'

Wyświetlenie wszystkich funkcji numpy:

In [ ]:
dir(np)

Wyświetlanie pomocy:

In [ ]:
help(np.array)

Tablica - array (wielowymiarowa tablica) jest podstawowym elementem numpy 

1D Array - tablica jednowymiarowa. Elementy tablicy podajemy jako elementy listy.

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


Sprawdzdenie typu obiektu. Jest to punkt w przestrzeni, wektor.

In [8]:
type(x)

numpy.ndarray

Wymiar tablicy:

In [9]:
x.ndim

1

Kształt tablicy, wyświetla się jako Tuple. Ponieważ mamy dwa elementy wyświetla się 2:

In [10]:
x.shape

(2,)

In [ ]:
Liczba elementów w tablicy:

In [11]:
x.size

2

Typ danych:

In [12]:
x.dtype

dtype('int64')

Przykład jednowymiarowej tablicy:

In [14]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [15]:
x.dtype

dtype('float64')

2D Array - tablice dwuwymiarowe. Domyślna interpretacja macierzy.

In [19]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [20]:
x.ndim

2

In [21]:
x.shape

(2, 2)

In [22]:
x = np.array([[1, 2, 4],[4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [23]:
x.shape

(2, 3)

3D Array - tablice trzy wymiarowe. Przechowują dane np. obrazy.

In [26]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3,],
     [4, 2, 1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [27]:
x.ndim

3

Parametr shape informuje nas, że mamy dwie tablice o dwóch wierszach i trzech kolumnach.

In [28]:
x.shape

(2, 2, 3)

In [30]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3,],
     [4, 2, 1]],
     
     [[4, 1, 3,],
     [4, 2, 1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [31]:
x.shape

(3, 2, 3)

TYPY DANYCH

In [32]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [33]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

Kontrolowanie typu danych, parametr dtype:

In [34]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

Inne typy danych np. complex - liczby złożone.

In [35]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

Typ danych int - liczby całkowite.

In [36]:
A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

dtype('int64')

Zdefiniowanie typu danych na liczby całkowite jednocześnie sprawi, że Python przekonwertuje liczby na całkowite:

In [38]:
A

array([1, 2, 3])

Typ danych bool - wartości logiczne prawda/fałsz

In [40]:
A = np.array([True, False])
A.dtype

dtype('bool')

Wbudowane typy danych numpy np. dla tablic opisujących zdjęcie, gdybyśmy chcieli przedstawić parametry pixela dla jakiegoś obrazu. int8 - 8mio bitowa liczba całkowita

In [41]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

uint8 - używa wartości od 0 do 255

In [42]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

TWORZENIE TABLIC

zeros - tworzy tablice dowolnych rozmiarów składającą się z samych 0. Domyślnie tworzy typ danych float.
Do stworzenia obrazu np 80 x 200 pikseli o czarnym tle można skorzystać z tej funkcji.

In [44]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Zdefiniowanie typu danych na int:

In [45]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Funkcja ones - tworzy tablice z liczbami 1

In [46]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Funkcja full - wypełni tablice konkretną wartością którą definiujemy

In [48]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

Funkcja arange generuje podane dane w postaci tablicy array.

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
np.arange(start=5, stop=20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Doadnie parametru kroku:

In [54]:
np.arange(start=5, stop=100, step=10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [55]:
np.arange(start=5, stop=-100, step=-10)

array([  5,  -5, -15, -25, -35, -45, -55, -65, -75, -85, -95])

In [56]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [58]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

Linspace - generuje równo rozłożone parametry z podanego przedziału

In [60]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [62]:
A = np.arange(15)

reshape - zmienia kształt danych:

In [64]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

W przypadku gdy chcemy aby dane zostały rozłożone przez Pythona jako drugi parametr podajemy -1. Wtedy powstaną 3 wiersze i dobrana przez Pythona liczba kolumn.

In [70]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [71]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

PODSTAWOWE OPERACJE NA TABLICACH

In [72]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


Dodawanie - dodawany jest element do elementu:

In [73]:
A + B

array([6, 0, 7, 4])

Odejmowanie:

In [74]:
A - B

array([0, 2, 1, 0])

Mnożenie:

In [75]:
A * B

array([ 9, -1, 12,  4])

Dzielenie (tablica nie może zawierać zera). Wynik będzie przekonwertowany na float nawet jeśli wcześniej były int:

In [76]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [77]:
A+3

array([6, 4, 7, 5])

In [78]:
A-3

array([ 0, -2,  1, -1])

In [79]:
A*3

array([ 9,  3, 12,  6])

In [80]:
A + 3*B

array([12, -2, 13,  8])

Numpy zawiera metody do wykonwyania działań.

In [81]:
np.add(A, B) #dodawanie dwóch tablic

array([6, 0, 7, 4])

In [82]:
np.subtract(A, B) #odejmowanie

array([0, 2, 1, 0])

In [83]:
np.multiply(A, B) #mnożenie

array([ 9, -1, 12,  4])

In [84]:
np.divide(A, B) #dzielenie

array([ 1.        , -1.        ,  1.33333333,  1.        ])

MNOŻENIE MACIERZOWE:

In [85]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [86]:
np.dot(X, Y) # mnożenie macierzowe, wiersz X kolumna

array([[  3,   6],
       [-12,   0]])

In [87]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [88]:
Y.dot(X) # mnożenie macierzy nie jest działaniem przemiennym!

array([[ 6, 18],
       [-5, -3]])

In [89]:
X @ Y # symbol @ też mnoży macierze

array([[  3,   6],
       [-12,   0]])

GENEROWANIE LICZB PSEUDOLOSYWCH:

In [90]:
np.random.seed(0)

In [91]:
np.random.randn()

1.764052345967664

In [92]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [95]:
np.random.randn(10, 4)

array([[ 1.22244507,  0.20827498,  0.97663904,  0.3563664 ],
       [ 0.70657317,  0.01050002,  1.78587049,  0.12691209],
       [ 0.40198936,  1.8831507 , -1.34775906, -1.270485  ],
       [ 0.96939671, -1.17312341,  1.94362119, -0.41361898],
       [-0.74745481,  1.92294203,  1.48051479,  1.86755896],
       [ 0.90604466, -0.86122569,  1.91006495, -0.26800337],
       [ 0.8024564 ,  0.94725197, -0.15501009,  0.61407937],
       [ 0.92220667,  0.37642553, -1.09940079,  0.29823817],
       [ 1.3263859 , -0.69456786, -0.14963454, -0.43515355],
       [ 1.84926373,  0.67229476,  0.40746184, -0.76991607]])

In [97]:
np.random.rand() #zwraca wartość losową z przedziało 0-1

0.05433798833925363

In [98]:
np.random.rand(10)

array([0.19999652, 0.01852179, 0.7936977 , 0.22392469, 0.34535168,
       0.92808129, 0.7044144 , 0.03183893, 0.16469416, 0.6214784 ])

In [99]:
np.random.rand(10, 2)

array([[0.57722859, 0.23789282],
       [0.934214  , 0.61396596],
       [0.5356328 , 0.58990998],
       [0.73012203, 0.311945  ],
       [0.39822106, 0.20984375],
       [0.18619301, 0.94437239],
       [0.7395508 , 0.49045881],
       [0.22741463, 0.25435648],
       [0.05802916, 0.43441663],
       [0.31179588, 0.69634349]])

In [101]:
np.random.randint(10) #zwróci wartośc z przedziału 0-9 losowo

1

In [103]:
np.random.randint(low=10, high=101) #losowa liczba z podanego przedziału

56

In [104]:
np.random.randint(low=10, high=101, size=10) # size definiuje ile liczb ma być wygenerowanych z podanego przedziału

array([31, 83, 99, 83, 38, 91, 68, 10, 96, 73])

In [106]:
np.random.choice([4, 2, 1, 4]) #losuje element z podanej listy

1

In [107]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [109]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
np.random.shuffle(data) # shuffle przetasuje dane, zmiana jest trwała
data

array([8, 0, 3, 2, 1, 6, 4, 9, 5, 7])

PODSTAWOWE FUNCKE NUMPY

Eksponent - exp

In [112]:
np.exp(1) #poda stałą eulera

2.718281828459045

In [113]:
np.sqrt(9) #pierwiastek, typ float

3.0

In [118]:
np.all([2, 3, 0]) # bada wartości pod kątem logicznym, 0 - false

False

In [117]:
np.any([0, 0, 0])

False

In [119]:
bool(0) # 0 false, pozostałe liczby true

False

In [121]:
A = np.random.rand(5)
A

array([0.8802976 , 0.31369239, 0.95745086, 0.47175157, 0.71158382])

In [122]:
np.argmax(A) # zwróci nam największą wartość

2

In [123]:
A[np.argmax(A)] # wycinanie największej wartości z wylosowanych

0.9574508556589537

In [124]:
np.argmin(A)

1

In [125]:
np.argsort(A) # nadaje kolejność (klasy) liczbą, od największej nr do najmniejszej 4

array([1, 3, 4, 0, 2])

In [126]:
np.min(A) #najmnieszja wartość

0.3136923925080297

In [127]:
np.mean(A) #średnia

0.6669552478471206

In [128]:
np.median(A) #mediana

0.7115838170608139

In [129]:
np.std(A) #odchylenie standardowe

0.2428141216478521

INDEKSOWANIE I WYCINANIE TABLIC

In [130]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[indeks który chcemy wyciąć],
# A[start:stop] indeks od którego chcemy zacząć, stop na którym chcemy skończyć
# # A[idx], A[start:stop], A[:stop], A[start:]

In [131]:
A[2]

2

In [132]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [133]:
A[:2]

array([0, 1])

In [135]:
A[[0,2]]

array([0, 2])

In [136]:
A[-1]

19

In [137]:
A[10:15]

array([10, 11, 12, 13, 14])

In [153]:
B = A.reshape(4, 5) #tablica dwuwymiarowa o wym. 4x5
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [155]:
B[1] #wycina cały pierwszy wiersz

array([5, 6, 7, 8, 9])

In [156]:
B[:, 0] #wycinanie kolumny

array([ 0,  5, 10, 15])

In [157]:
B[:, -1] #wycinanie ostatniej kolumny

array([ 4,  9, 14, 19])

In [158]:
#wycinanie konkretnego elementu np.6 - podajemy indeksy miejsca
B[1,1]

6

In [159]:
B[3,2]

17

In [162]:
#wycinanie przedziału, pierwszy zakres oznacza wiersze - przy czym przy zdefiniowaniu wierszy od 1 do 3 wyświetlone zostaną dwa wiersze.
# druga cyfra oznacza kolumny, tak samo przy wyświetleniu od 1 do 4 wyświetlone zostaną dane z 3 kolumn
B[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [165]:
B[1, 2] = 14 # przypisanie nowej wartości do tablicy / zmiana liczby 7 na 14

In [166]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

ITERACJA PO TABLICACH
Za pomocą pętli:

In [168]:
for row in B:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [170]:
for row in B:
  print(row[3])

3
8
13
18


In [171]:
for row in B:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [172]:
for item in A.flat: #flat wypłaszcza tablice
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


ZMIANA ROZMIARU TABLIC:

In [179]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [173]:
B.shape # podaje ilość wierszy i kolumn tablicy

(4, 5)

In [174]:
B.reshape(5,4) # zmienia rozkład wierszy i kolumn na podany

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [177]:
B.ravel() # wypłaszcza dane

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [178]:
B.T # zamienia kolumny na wierwsze

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

MASKI LOGICZNE

In [183]:
A = np.arange(start=-10, stop=10, step=0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [184]:
A.reshape(10, -1) #zmiana rozkładu tablicy na 10 wierszy i dobraną liczbę kolumn

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [185]:
#mapki logiczne - chcemy sprawdzić w których miejscach mamy wartości ujemne
A > 0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [186]:
A[A>0] # wytnie nam wartości wg warunku logicznego

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [188]:
np.bitwise_and(A > -5, A < 5) # zastępuje nam warunek A > -5 and A < 5 bo numpy nie rozumie takiego warunku logicznego

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [189]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [190]:
np.bitwise_or(A < -5, A > 5)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])