<a href="https://colab.research.google.com/github/Atria14/data-science/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

FUNCKCJE STATYSTYCZNE

In [3]:
import numpy as np

In [4]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


sum()

In [5]:
price.sum() # suma wszystkich elmentów znajdujących się w tablicy

4650.1

In [7]:
price.sum(axis=0) # wartość suma poszczególnych kolumn - 0

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [ ]:
price.sum(axis=1) # wartość suma poszczególnych wierszy - 1

In [8]:
np.sum(price)

4650.1

min()

In [9]:
np.min(price) # minimum z całej tablicy

11.7

In [10]:
np.min(price, axis = 0) # wartości minimalne z każdej kolumny

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [11]:
np.min(price, axis = 1) # wartości minimalne z każdego wiersza

array([11.9, 11.7, 12.2])

median()

In [12]:
np.median(price)

12.6

mean() - średnia danych

In [13]:
np.mean(price,axis=0) # zwykle axis=0 bo liczy się to po kolumnach

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

std() - odchylenie standardowe

In [14]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

var()

In [15]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])

In [16]:
    X = np.array([2., -3, 4])
    print(X.dtype)

float64


In [23]:
np.random.randn(10)

array([-0.12359605, -0.46587145, -2.29514852,  0.31184598,  1.95815692,
        0.45598125,  0.41211663,  0.38456758,  1.12833162,  2.03494836])

In [24]:
np.random.randint(10)

1

In [27]:
np.random.rand(10)

array([0.66586729, 0.82494927, 0.27791139, 0.97462639, 0.33917104,
       0.42700247, 0.68815886, 0.65560927, 0.62661076, 0.05227647])