<a href="https://colab.research.google.com/github/Atria14/data-science/blob/main/template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Colab')

Hello Colab


In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.6'

Wyświetlenie wszystkich funkcji numpy:

In [ ]:
dir(np)

Wyświetlanie pomocy:

In [ ]:
help(np.array)

Tablica - array (wielowymiarowa tablica) jest podstawowym elementem numpy 

1D Array - tablica jednowymiarowa. Elementy tablicy podajemy jako elementy listy.

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


Sprawdzdenie typu obiektu. Jest to punkt w przestrzeni, wektor.

In [8]:
type(x)

numpy.ndarray

Wymiar tablicy:

In [9]:
x.ndim

1

Kształt tablicy, wyświetla się jako Tuple. Ponieważ mamy dwa elementy wyświetla się 2:

In [10]:
x.shape

(2,)

In [ ]:
Liczba elementów w tablicy:

In [11]:
x.size

2

Typ danych:

In [12]:
x.dtype

dtype('int64')

Przykład jednowymiarowej tablicy:

In [14]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [15]:
x.dtype

dtype('float64')

2D Array - tablice dwuwymiarowe. Domyślna interpretacja macierzy.

In [19]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [20]:
x.ndim

2

In [21]:
x.shape

(2, 2)

In [22]:
x = np.array([[1, 2, 4],[4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [23]:
x.shape

(2, 3)

3D Array - tablice trzy wymiarowe. Przechowują dane np. obrazy.

In [26]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3,],
     [4, 2, 1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [27]:
x.ndim

3

Parametr shape informuje nas, że mamy dwie tablice o dwóch wierszach i trzech kolumnach.

In [28]:
x.shape

(2, 2, 3)

In [30]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3,],
     [4, 2, 1]],
     
     [[4, 1, 3,],
     [4, 2, 1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [31]:
x.shape

(3, 2, 3)

TYPY DANYCH

In [32]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [33]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

Kontrolowanie typu danych, parametr dtype:

In [34]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

Inne typy danych np. complex - liczby złożone.

In [35]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

Typ danych int - liczby całkowite.

In [36]:
A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

dtype('int64')

Zdefiniowanie typu danych na liczby całkowite jednocześnie sprawi, że Python przekonwertuje liczby na całkowite:

In [38]:
A

array([1, 2, 3])

Typ danych bool - wartości logiczne prawda/fałsz

In [40]:
A = np.array([True, False])
A.dtype

dtype('bool')

Wbudowane typy danych numpy np. dla tablic opisujących zdjęcie, gdybyśmy chcieli przedstawić parametry pixela dla jakiegoś obrazu. int8 - 8mio bitowa liczba całkowita

In [41]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

uint8 - używa wartości od 0 do 255

In [42]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

TWORZENIE TABLIC

zeros - tworzy tablice dowolnych rozmiarów składającą się z samych 0. Domyślnie tworzy typ danych float.
Do stworzenia obrazu np 80 x 200 pikseli o czarnym tle można skorzystać z tej funkcji.

In [44]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Zdefiniowanie typu danych na int:

In [45]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Funkcja ones - tworzy tablice z liczbami 1

In [46]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Funkcja full - wypełni tablice konkretną wartością którą definiujemy

In [48]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

Funkcja arange generuje podane dane w postaci tablicy array.

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
np.arange(start=5, stop=20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Doadnie parametru kroku:

In [54]:
np.arange(start=5, stop=100, step=10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [55]:
np.arange(start=5, stop=-100, step=-10)

array([  5,  -5, -15, -25, -35, -45, -55, -65, -75, -85, -95])

In [56]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [58]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

Linspace - generuje równo rozłożone parametry z podanego przedziału

In [60]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [62]:
A = np.arange(15)

reshape - zmienia kształt danych:

In [64]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

W przypadku gdy chcemy aby dane zostały rozłożone przez Pythona jako drugi parametr podajemy -1. Wtedy powstaną 3 wiersze i dobrana przez Pythona liczba kolumn.

In [70]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [71]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

PODSTAWOWE OPERACJE NA TABLICACH

In [72]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


Dodawanie - dodawany jest element do elementu:

In [73]:
A + B

array([6, 0, 7, 4])

Odejmowanie:

In [74]:
A - B

array([0, 2, 1, 0])

Mnożenie:

In [75]:
A * B

array([ 9, -1, 12,  4])

Dzielenie (tablica nie może zawierać zera). Wynik będzie przekonwertowany na float nawet jeśli wcześniej były int:

In [76]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [77]:
A+3

array([6, 4, 7, 5])

In [78]:
A-3

array([ 0, -2,  1, -1])

In [79]:
A*3

array([ 9,  3, 12,  6])

In [80]:
A + 3*B

array([12, -2, 13,  8])

Numpy zawiera metody do wykonwyania działań.

In [81]:
np.add(A, B) #dodawanie dwóch tablic

array([6, 0, 7, 4])

In [82]:
np.subtract(A, B) #odejmowanie

array([0, 2, 1, 0])

In [83]:
np.multiply(A, B) #mnożenie

array([ 9, -1, 12,  4])

In [84]:
np.divide(A, B) #dzielenie

array([ 1.        , -1.        ,  1.33333333,  1.        ])

MNOŻENIE MACIERZOWE:

In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)